server:
  port: 8083
  maxHttpPostSize: 10485760
  tomcat:
    max-threads: 500
management:
  port: 3033
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
     execution:
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 4000
          thread:
            timeoutInMilliseconds: 30000
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1500
ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0